#!/usr/bin/env bash
set -euo pipefail
: "${CANDIDATE:?}"; : "${RUN_NAME:?}"; : "${START_DATE:?}"; : "${EVAL_DATE:?}"; : "${END_DATE:?}"; : "${CALIBRATION_MANIFEST:?}"
case "$CANDIDATE" in
 V60_CORE_L0_BASELINE) GRID=false; ADAPTIVE=false; CAPLIVE=false; VARIANT=CORE_L0_BASELINE;;
 V60_CORE_L0_FAMILY_CAPTURE) GRID=false; ADAPTIVE=false; CAPLIVE=true; VARIANT=CORE_L0_FAMILY_CAPTURE;;
 V60_LEGACY_FIB_GRID_CAPTURE) GRID=true; ADAPTIVE=false; CAPLIVE=true; VARIANT=LEGACY_FIB_GRID_CAPTURE;;
 V60_ADAPTIVE_FIB_GRID_CAPTURE) GRID=true; ADAPTIVE=true; CAPLIVE=true; VARIANT=ADAPTIVE_FIB_GRID_CAPTURE;;
 *) echo "unsupported V60 candidate $CANDIDATE"; exit 31;;
esac
CALMAN=$(tr -d '\n\r' < "$CALIBRATION_MANIFEST"); test -n "$CALMAN"
FAMNATIVE=false FAMOBS=true CANCONTRACT=true FAMCONF=true GRIDV2=true STOPV2=true JOINT=true CORRIDOR=false ANCHORFORENSICS=true \
IDENT=true BOUNDED=true SKIPS=2 FQUOTA=4 PRJPRZ=false DTRUTH=true TRADING=true FAMILYBOOKS=true SHADOW=true CALADMIT=true FAMREP=true RESEARCHCONT=true \
ABCDLIVE=false V60GRID="$GRID" V60VARIANT="$VARIANT" V60ADAPTIVE="$ADAPTIVE" V60CONVEX=true V60RUNNER=true V60RUNNERFRAC=.25 V60CLUSTER=true V60SURFACE=true V60SCHED=true \
CALMIN=0.0 CALMAN="$CALMAN" MANIFOLD=true PUREPRZ=true DAG=true CAPRESEARCH=true CAPLIVE="$CAPLIVE" MATCHED=true PROJERR=.55 MSIG=1.0 \
PQUEUE=false HANDOFF=false NATIVE=false NATIVEBARS=4 DECAY=false HARDLIFE=180 REVALIDATE=false \
"$GITHUB_WORKSPACE/control/HarmonyBot-V60/tools/run_backtest.sh"
