<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <RootNamespace>cAlgo.Robots</RootNamespace>
    <AlgoName>xauusd_3_v37</AlgoName>
    <AlgoType>Robot</AlgoType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="src/FibonacciXAUUSD3V37.cs" />
    <PackageReference Include="cTrader.Automate" Version="1.0.19" />
  </ItemGroup>
</Project>
