import pathlib
s=pathlib.Path("HarmonyBot-V62/src/HarmonyBotV62.cs").read_text()
for x in ["V62_V51_EXACT_CONTROL","V62_DAG_SINGLE_ENTRY","V62_CURRENT_V61_GRID","V62_FRONT_LOADED_GRID","V62_CONDITIONAL_GRID","V62_CONDITIONAL_STRUCTURAL_EXIT","V62_CONDITIONAL_RUNNER","V62_PATTERN_NATIVE"]:assert x in s,x
print("PASS")
