<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>CumulativeDeltaScalper_K_Commercial_v3</AssemblyName>
    <RootNamespace>cAlgo.Robots</RootNamespace>
    <AlgoName>CumulativeDeltaScalper_K_Commercial_v3</AlgoName>
    <AlgoBuild>true</AlgoBuild>
    <AlgoPublish>false</AlgoPublish>
    <IncludeSource>true</IncludeSource>
    <IncludeSymbols>false</IncludeSymbols>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="**/*.cs" />
    <Compile Include="src/CumulativeDeltaScalper_K_Commercial_v3.cs" />
    <PackageReference Include="cTrader.Automate" Version="1.*-*" />
  </ItemGroup>
</Project>
