<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>HarmonyBot</AssemblyName>
    <RootNamespace>cAlgo.Robots</RootNamespace>
    <AlgoName>HarmonyBot-Mobile</AlgoName>
    <AlgoBuild>true</AlgoBuild>
    <AlgoPublish>false</AlgoPublish>
    <IncludeSource>true</IncludeSource>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="cTrader.Automate" Version="1.0.19" />
  </ItemGroup>
</Project>
