from pathlib import Path
import sys
s=Path(sys.argv[1] if len(sys.argv)>1 else 'HarmonyBot-v19/HarmonyBotPro_v19_50PASS.cs').read_text()
checks=[]
def ck(name, cond): checks.append((name,bool(cond)))
ck('01 namespace cAlgo.Robots','namespace cAlgo.Robots' in s)
ck('02 Robot AccessRights.None','AccessRights = AccessRights.None' in s)
ck('03 main class unique',s.count('public class HarmonyBotPro : Robot')==1)
ck('04 braces balanced',s.count('{')==s.count('}'))
ck('05 no Position.ClosePrice API use','p.ClosePrice' not in s)
ck('06 completed signal bar','int signalIndex = _signalBars.Count - 2;' in s)
ck('07 completed H1 EMA','h1.Count - 2' in s)
ck('08 completed H4 EMA','h4.Count - 2' in s)
ck('09 completed ATR','int idx = _signalBars.Count - 2;' in s)
ck('10 latest regime window','int endIndex = _signalBars != null ? _signalBars.Count - 2 : -1;' in s)
ck('11 risk raw below broker min skip','raw < _symbol.VolumeInUnitsMin' in s)
ck('12 risk post-normalization cap','actualRisk > maxAllowed' in s)
ck('13 max risk overshoot parameter','MaxRiskOvershootPercent' in s)
ck('14 no hedge parameter','public bool NoHedging' in s)
ck('15 single position parameter','public bool EnforceSinglePosition' in s)
ck('16 no hedge gate','p.TradeType != tt' in s)
ck('17 single position gate','EnforceSinglePosition && open.Length > 0' in s)
ck('18 max concurrent default 1','Max Concurrent Trades", DefaultValue = 1' in s)
ck('19 hard DD parameter','AbsoluteHardDrawdownPercent' in s)
ck('20 DD cooldown parameter','DrawdownCooldownHours' in s)
ck('21 recovery risk factor','RecoveryRiskFactor' in s)
ck('22 hard DD permanent safety stop','AbsoluteHardDD' in s)
ck('23 soft DD cooldown','MaxDDCooldown' in s)
ck('24 recovery unlock','Drawdown cooldown completed' in s)
ck('25 recovery target','_drawdownRecoveryTarget' in s)
ck('26 native NetProfit stats','double moneyPnl = p.NetProfit;' in s)
ck('27 risk money tracked','_initialRiskMoney' in s)
ck('28 R based on money risk','moneyPnl / riskMoney' in s)
ck('29 breakeven not counted win','else { s.Breakevens++; }' in s)
ck('30 ledger gross money PF','s.GrossWinMoney / s.GrossLossMoney' in s)
ck('31 tracker observed equity DD','ObserveEquity' in s)
ck('32 partial TP default off','Enable Partial TP", DefaultValue = false' in s)
ck('33 TP1 reduced share','TP1 Close %", DefaultValue = 30.0' in s)
ck('34 R-aware break even','initialRiskPips * 0.80' in s)
ck('35 R-aware trailing trigger','initialRiskPips * 1.50' in s)
ck('36 R-aware trailing distance','initialRiskPips * 0.60' in s)
ck('37 pattern confidence adjusted','Pattern Confidence", DefaultValue = 0.68' in s)
ck('38 entry deviation adjusted','Max Entry Dev (ATR)", DefaultValue = 0.8' in s)
ck('39 pattern age parameter','Max Pattern Age Bars' in s)
ck('40 family-aware scan','for (int i = start; i < pivots.Count; i++)' in s)
ck('41 reversal bounds guard','!isShark && !isFiveZero && !isAbcd && i + 4 >= pivots.Count' in s)
ck('42 ABCD bounds guard','isAbcd && i + 3 >= pivots.Count' in s)
ck('43 Shark bounds guard','isShark && i + 3 >= pivots.Count' in s)
ck('44 5-0 bounds guard','isFiveZero && i + 4 >= pivots.Count' in s)
ck('45 grouping completion index','int key = c.CompletionIndex;' in s)
ck('46 pattern completion age gate','completionAge > _maxPatternAgeBars' in s)
ck('47 current closed close confirm','bars.ClosePrices[currentIndex]' in s)
ck('48 ABCD bullish-bearish reversal polarity','bull = (b.Price < a.Price) && (c.Price > b.Price) && (d.Price < c.Price);' in s)
ck('49 XABCD AD-XA completion geometry','double rAD = ad / xa;' in s and 'rXD = xd / xa' not in s)
ck('50 valid Fib zone tolerance semantics','double lo = Math.Max(0.0, min - _fibTolerance);' in s and 'double hi = max + _fibTolerance;' in s)
failed=[n for n,ok in checks if not ok]
for n,ok in checks: print(('PASS' if ok else 'FAIL'),n)
print(f'RESULT {len(checks)-len(failed)}/{len(checks)} passed')
if failed: raise SystemExit('FAILED: '+', '.join(failed))
